export const segmentIds = {
  'Miscellaneous': "KZFzniwnSyZfZ7v7n1",
  'Sports': "KZFzniwnSyZfZ7v7nE",
  'Music: "KZFzniwnSyZfZ7v7nJ",
  'ArtsTheatre': "KZFzniwnSyZfZ7v7na",
  'Undefined': "KZFzniwnSyZfZ7v7nl",
  'Film': "KZFzniwnSyZfZ7v7nn"
};

export const genreIdsMiscellaneous = {
  'Casino/Gaming': "KnvZfZ7vAAa",
  'Comedy': "KnvZfZ7vAA1",
  'Community/Civic': "KnvZfZ7vAAE",
  'Community/Cultural': "KnvZfZ7v7lE",
  'Fairs & Festivals': "KnvZfZ7vAeE",
  'Family': "KnvZfZ7vA1n",
  'Food & Drink': "KnvZfZ7vAAI",
  'Health/Wellness': "KnvZfZ7vAAl",
  'Hobby/Special Interest Expos': "KnvZfZ7vAAJ",
  'Holiday': "KnvZfZ7vAAt",
  'Ice Shows': "KnvZfZ7v7lI",
  'Multimedia': "KnvZfZ7vAAF",
  'Psychics/Mediums/Hypnotists': "KnvZfZ7vAAn",
  'Special Interest/Hobby': "KnvZfZ7v7lt",
  'Undefined': "KnvZfZ7v7ll",
};

export const genreIdsSports = {
  'Aquatics': "KnvZfZ7vAeI",
  'Athletic Races': "KnvZfZ7vAet",
  'Badminton': "KnvZfZ7vAen",
  'Bandy': "KnvZfZ7vAel",
  'Baseball': "KnvZfZ7vAdv",
  'Basketball': "KnvZfZ7vAde",
  'Biathlon': "KnvZfZ7vAdd",
  'Body Building': "KnvZfZ7vAd7",
  'Boxing': "KnvZfZ7vAdA",
  'Cricket': "KnvZfZ7vAdk",
  'Curling': "KnvZfZ7vAdF",
  'Cycling': "KnvZfZ7vAda",
  'Equestrian': "KnvZfZ7vAd1",
  'Extreme': "KnvZfZ7vAdJ",
  'Floorball': "KnvZfZ7vA1l",
  'Football': "KnvZfZ7vAdE",
  'Golf': "KnvZfZ7vAdt",
  'Gymnastics': "KnvZfZ7vAdn",
  'Handball': "KnvZfZ7vAdl",
  'Hockey': "KnvZfZ7vAdI",
  'Ice Skating': "KnvZfZ7vA7v",
  'Indoor Soccer': "KnvZfZ7vA7e",
  'Lacrosse': "KnvZfZ7vA77",
  'Martial Arts': "KnvZfZ7vA7d",
  'Miscellaneous': "KnvZfZ7vA7A",
  'Motorsports/Racing': "KnvZfZ7vA7k",
  'Netball': "KnvZfZ7vA76",
  'Rodeo': "KnvZfZ7vAea",
  'Roller Hockey': "KnvZfZ7vA7a",
  'Rugby': "KnvZfZ7vA71",
  'Ski Jumping': "KnvZfZ7vA7J",
  'Skiing': "KnvZfZ7vAd6",
  'Soccer': "KnvZfZ7vA7E",
  'Squash': "KnvZfZ7vA7I",
  'Surfing': "KnvZfZ7vA7t",
  'Swimming': "KnvZfZ7vA7n",
  'Table Tennis': "KnvZfZ7vA7l",
  'Tennis': "KnvZfZ7vAAv",
  'Toros': "KnvZfZ7vAAe",
  'Track & Field': "KnvZfZ7vAAd",
  'Volleyball': "KnvZfZ7vAA7",
  'Waterpolo': "KnvZfZ7vAAA",
  'Wrestling': "KnvZfZ7vAAk",
  'Field Hockey': "KnvZfZ7vAJv",
}

export const genreIdsMusic = {
  'Alternative': "KnvZfZ7vAvv",
  'Ballads/Romantic': "KnvZfZ7vAve",
  'Blues': "KnvZfZ7vAvd",
  'Chanson Francaise': "KnvZfZ7vAvA",
  'Children's Music': "KnvZfZ7vAvk",
  'Classical': "KnvZfZ7vAeJ",
  'Country': "KnvZfZ7vAv6",
  'Dance/Electronic': "KnvZfZ7vAvF",
  'Folk': "KnvZfZ7vAva",
  'Hip-Hop/Rap': "KnvZfZ7vAv1",
  'Holiday': "KnvZfZ7vAvJ",
  'Jazz': "KnvZfZ7vAvE",
  'Medieval/Renaissance': "KnvZfZ7vAvI",
  'Metal': "KnvZfZ7vAvt",
  'New Age': "KnvZfZ7vAvn",
  'Other': "KnvZfZ7vAvl",
  'Pop': "KnvZfZ7vAev",
  'R&B': "KnvZfZ7vAee",
  'Reggae': "KnvZfZ7vAed",
  'Religious': "KnvZfZ7vAe7",
  'Rock': "KnvZfZ7vAeA",
  'Undefined': "KnvZfZ7vAe6",
  'World': "KnvZfZ7vAeF",
}

export const genreIdsArtsTheatre = {
  'Children's Theatre': "KnvZfZ7v7na",
  'Circus & Specialty Acts': "KnvZfZ7v7n1",
  'Classical': "KnvZfZ7v7nJ",
  'Comedy': "KnvZfZ7vAe1",
  'Cultural': "KnvZfZ7v7nE",
  'Dance': "KnvZfZ7v7nI",
  'Espectaculo': "KnvZfZ7v7nt",
  'Fashion': "KnvZfZ7v7nn",
  'Fine Art': "KnvZfZ7v7nl",
  'Magic & Illusion': "KnvZfZ7v7lv",
  'Miscellaneous': "KnvZfZ7v7le",
  'Miscellaneous Theatre': "KnvZfZ7v7ld",
  'Multimedia': "KnvZfZ7v7l7",
  'Music': "KnvZfZ7v7lA",
  'Opera': "KnvZfZ7v7lk",
  'Performance Art': "KnvZfZ7v7l6",
  'Puppetry': "KnvZfZ7v7lF",
  'Spectacular': "KnvZfZ7v7la",
  'Theatre': "KnvZfZ7v7l1",
  'Variety': "KnvZfZ7v7lJ",
}

export const genreIdsUndefined = {
  'Undefined': "KnvZfZ7vAkI",
}

export const genreIdsFilm = {
  'Action/Adventure': "KnvZfZ7vAke",
  'Animation': "KnvZfZ7vAkd",
  'Arthouse': "KnvZfZ7vAk7",
  'Comedy': "KnvZfZ7vAkA",
  'Documentary': "KnvZfZ7vAkk",
  'Drama': "KnvZfZ7vAk6",
  'Family': "KnvZfZ7vAkF",
  'Foreign': "KnvZfZ7vAk1",
  'Miscellaneous': "KnvZfZ7vAka",
  'Music': "KnvZfZ7vAkJ",
  'Urban': "KnvZfZ7vAkE",
}